# Generated by Django 2.1 on 2018-08-23 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('winner', models.CharField(max_length=50)),
                ('loser', models.CharField(max_length=50)),
                ('faction_won', models.CharField(max_length=100)),
                ('faction_lost', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('chassis', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battles.Battle')),
            ],
        ),
    ]
