# Generated by Django 2.1 on 2018-08-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0003_auto_20180823_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_id',
            field=models.IntegerField(default=0),
        ),
    ]
