# Generated by Django 2.1 on 2018-08-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0004_auto_20180828_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='destroyed_by',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='battle',
            name='datetime',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='battle',
            name='faction_lost',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='battle',
            name='faction_won',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='battle',
            name='loser',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='battle',
            name='winner',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='chassis',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='model',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='owner',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
