# Generated by Django 2.1 on 2018-09-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0006_unit_battle_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='destroyed_by',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
